### ISSUE TITLE
Add ability to remove banned/required tags

### ISSUE THREAD

**Issue by n0wme** [catjacks38/HentaiDiscordBot#20]

**Comment by n0wme** [comment]
could be command like`.nhentai remove banned=yuri`

**Comment by catjacks38** [comment]
Yeah, something like that would well work. I'm working on other projects at the moment, so I won't be able to work on it immediately. I will notify you when it is implemented.

**Comment by catjacks38** [comment]
@n0wme This issue is resolved now.
